groups:
    - bash
recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::tap_to_click
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: PurpleNurple
    homebrewalt:
        apps:
            - git
            - git-extras
            - gti
            - wget
            - htop-osx
            - rsync
            - ack
            - autoconf
            - autojump
            - boot2docker
            - dos2unix
            - go
            - gradle
            - markdown
            - mongodb
            - mysql 
            - rbenv
            - rbenv-gemset
            - vim 
            - tree
            - unrar
            - heroku-toolbelt
            - phantomjs
            - pkg-config
            - postgresql
            - pyenv
            - qt
            - ssh-copy-id
            - ruby-build
            - readline
            - the_silver_searcher
        cask_apps:
            - 1password
            - dash
            - caffeine
            - screenhero
            - kaleidoscope
            - vlc
            - vagrant
            - virtualbox
            - plug
            - hipchat
            - evernote
            - spotify
            - slack
            - fantastical
            - bartender
            - sizeup
    dotfiles:
        vimusers:
            - root
            - pamo
        vim:
            bundle:
                - sensible: git://github.com/tpope/vim-sensible.git
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - airline: https://github.com/bling/vim-airline
                - vim-css-color: https://github.com/ap/vim-css-color
                - syntastic: git://github.com/scrooloose/syntastic.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - nerdtree: git://github.com/scrooloose/nerdtree.git
                - surround: git://github.com/tpope/vim-surround.git
                - ctrlp: git://github.com/kien/ctrlp.vim.git
                - sessionman: git://github.com/vim-scripts/sessionman.vim.git
                - matchit: git://github.com/vim-scripts/matchit.zip.git
                - easymotion: git://github.com/Lokaltog/vim-easymotion.git
                - nerdtreetabs: git://github.com/jistr/vim-nerdtree-tabs.git
                - undotree: git://github.com/mbbill/undotree.git
                - numbers: git://github.com/myusuf3/numbers.vim.git
                - tmux: git://github.com/christoomey/vim-tmux-navigator.git
                - sbt: git://github.com/derekwyatt/vim-sbt.git
                - screen: git://github.com/ervandew/screen.git
                - fireplace: git://github.com/tpope/vim-fireplace.git
                - classpath: git://github.com/tpope/vim-classpath.git
                - clojure: git://github.com/guns/vim-clojure-static.git
                - expand: git://github.com/terryma/vim-expand-region.git
                - rails: git://github.com/tpope/vim-rails.git
                - lightline: git://github.com/itchyny/lightline.vim.git
                - javascript: git://github.com/pangloss/vim-javascript.git
                - jsx: git://github.com/mxw/vim-jsx.git
    git:
        name: Pamela Ocampo
        email: pamela.ocampo@gmail.com
    nodejs:
        apps:
            - bower
            - grunt
            - grunt-cli
