recipes:                                       # Configs are parsed and every list is appended to each other, chef handles order and de-duplication
    global:                                    # Recipes mentioned under "global" are installed for all operating systems (we used to support linux, and may do so in the future)
        - applications::create_var_chef_cache
    mac_os_x:                                  # Recipes mentioned under "mac_os_x" are installed on OSX and OSX Server
        - homebrewalt::default                 # Installs homebrew and homebrew cask and installs all apps mentioned in the homebrewalt:apps and homebrewalt:cask_apps attributes
        - nodejs::default                      # Installs nodejs and installs all nodejs packages mentioned in the nodejs:apps attribute
	- dotfiles::inputrc
	- osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
	- osxdefaults::dock_set_magnification_on
	- osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
	- osxdefaults::enable_safari_debug_menu
	- osxdefaults::finder_display_full_path
	- osxdefaults::finder_set_preferred_view_style
	- osxdefaults::finder_show_all_files
	- osxdefaults::finder_show_file_extensions
	- osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_small_sidebar_icon_size
	- osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
	- osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
        - osxdefaults::tap_to_click
        - osxdefaults::set_computer_name
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
	- osxdefaults::enable_assistive_devices
attributes:
    osxdefaults:
	computername: pamo
    homebrewalt:
        apps:
	    - ack
	    - autoconf
	    - autojump
	    - boot2docker
	    - dos2unix
	    - go
	    - gradle
	    - markdown
	    - mongodb
	    - mysql 
	    - rbenv
	    - rbenv-gemset
	    - vim 
	    - tree
	    - unrar
	    - gcc
	    - heroku-toolbelt
	    - phantomjs
	    - pkg-config
	    - postgresql
	    - python
	    - qt
	    - ssh-copy-id
	    - ruby-build
   	    - readline
	    - git
	    - gti
        cask_apps:
            - google-chrome
            - mailplane
            - screenhero
	    - alfred
	    - dropbox
	    - virtualbox
	    - sublime-text
	    - iterm2
            - firefox
            - java
	    - 1password
	    - intellij-idea
	    - plug
	    - hipchat
	    - evernote
	    - flux
	    - spotify
	    - slack
	    - fantastical
	    - bartender
        cask_fonts:   
            - inconsolata
    nodejs:
        apps:
            - bower
