recipes:
    global:
        - dotfiles::gitconfig
        - applications::ssh_config
        - dotfiles::vim
        - dotfiles::workspace
    mac_os_x:
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row
        - osxdefaults::enable_standard_function_keys
        - osxdefaults::enable_safari_debug_menu
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::tap_to_click
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
attributes:
    mysql_root_password: "password"
    homebrewalt:
        apps:
            - git
            - git-extras
            - gti
            - wget
            - htop-osx
            - rsync
            - ack
            - autoconf
            - autojump
            - boot2docker
            - dos2unix
            - go
            - gradle
            - markdown
            - mongodb
            - mysql 
            - rbenv
            - rbenv-gemset
            - vim 
            - tree
            - unrar
            - gcc
            - heroku-toolbelt
            - phantomjs
            - pkg-config
            - postgresql
            - python
            - qt
            - ssh-copy-id
            - ruby-build
            - readline
    nodejs:
        apps:
            - bower
            - grunt
            - grunt-cli
